CREATE TABLE amenities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    icon VARCHAR(50)
);

INSERT INTO amenities (name, icon) VALUES
    ('WiFi', 'wifi'),
    ('Kitchen', 'kitchen'),
    ('Parking', 'parking'),
    ('Air Conditioning', 'ac'),
    ('Heating', 'heating'),
    ('TV', 'tv'),
    ('Washer', 'washer'),
    ('Dryer', 'dryer'),
    ('Pool', 'pool'),
    ('Hot Tub', 'hot_tub'),
    ('Gym', 'gym'),
    ('Breakfast', 'breakfast'),
    ('Pet Friendly', 'pets'),
    ('Smoking Allowed', 'smoking'),
    ('EV Charger', 'ev_charger');
